### ISSUE TITLE
릴리즈 서버 만들어놓기

### ISSUE THREAD

**Issue by mango-tree** [team-blackhole/UNIST-group-list-backend#21]
@pelly-ryu 스테이징 서버 따로 있을 필요 있을까요?
필요하면 하나 더 만듭시다

**Comment by pelly-ryu** [comment]
일단 서버 하나로 개발 쭉쭉하면서 생각하는 건 어떨까여
이건 PM님 관리 여력에 따라... ㅋㅋㅋ

**Comment by mango-tree** [comment]
그럼 릴리즈용으로 구글 앱 엔진에 하나만 올리는걸로 할게여
